name: Update copyright year(s) in license file

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 1 1 *" # 03:00 AM on January 1

jobs:
  update-years:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Change global git configurations
        run: |
          git config --global push.default current
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge pull request
        run: |
          export year=$(date +"%Y")
          perl -i -pe 's/(?<=\([cC]\)\s)(?<from>\d+)(-\d+)?/$+{from}-$ENV{"year"}/' README.md *.py
          git add --update
          git commit -m "Copyright year update"
          git remote set-url origin --push https://updater:${{ secrets.TOKEN }}@github.com/scmanjarrez/netauditor.git
          git remote set-url origin --add --push https://updater:${{ secrets.TOKENGL }}@gitlab.gast.it.uc3m.es/schica/netauditor.git
          git push
